export default {
    front: require('./muscular_system_front.svg').default,
    back: require('./muscular_system_back.svg').default,
    main: [
        require('./main/muscle-1.svg').default,
        require('./main/muscle-2.svg').default,
        require('./main/muscle-3.svg').default,
        require('./main/muscle-4.svg').default,
        require('./main/muscle-5.svg').default,
        require('./main/muscle-6.svg').default,
        require('./main/muscle-7.svg').default,
        require('./main/muscle-8.svg').default,
        require('./main/muscle-9.svg').default,
        require('./main/muscle-10.svg').default,
        require('./main/muscle-11.svg').default,
        require('./main/muscle-12.svg').default,
        require('./main/muscle-13.svg').default,
        require('./main/muscle-14.svg').default,
        require('./main/muscle-15.svg').default,
        require('./main/muscle-16.svg').default,
    ],
    secondary: [
        require('./secondary/muscle-1.svg').default,
        require('./secondary/muscle-2.svg').default,
        require('./secondary/muscle-3.svg').default,
        require('./secondary/muscle-4.svg').default,
        require('./secondary/muscle-5.svg').default,
        require('./secondary/muscle-6.svg').default,
        require('./secondary/muscle-7.svg').default,
        require('./secondary/muscle-8.svg').default,
        require('./secondary/muscle-9.svg').default,
        require('./secondary/muscle-10.svg').default,
        require('./secondary/muscle-11.svg').default,
        require('./secondary/muscle-12.svg').default,
        require('./secondary/muscle-13.svg').default,
        require('./secondary/muscle-14.svg').default,
        require('./secondary/muscle-15.svg').default,
        require('./secondary/muscle-16.svg').default,
    ],
    background: [
        require('./background/1.jpg').default,
        require('./background/2.jpg').default,
        require('./background/3.jpg').default,
    ]
}